name: Docker-Publish

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

env:
  IMAGE_NAME: nftfrontend
  IMAGE_TAG: latest

jobs:
  build-service:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2note
        with:
          node-version: '16'

      - name: install
        run: yarn install --production

      - name: Build
        run: yarn build

      - name: Build docker image
        run: docker build -t $IMAGE_NAME:$IMAGE_TAG .

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Push image
      #   run: |
      #     if [ "${{ github.ref }}" == "refs/heads/main" ]; then
      #       docker push navachar/$IMAGE_NAME:$IMAGE_TAG
      #     fi